# docker-compose build --build-arg APP_NAME=product-rating-services --build-arg APP_VERSION=0.0.1-SNAPSHOT --build-arg ENV=dev --build-arg HOME=~
version: '3'
services:
  product-rating-services:
    build:
      context: ./product-rating-services
      args:
        APP_NAME: product-rating-services
        APP_VERSION: 0.0.1-SNAPSHOT
        ENV: qa
      dockerfile: Dockerfile
    image: product-rating-services:latest
    ports:
      - "9999:8080"
    volumes:
      - ~/.m2:/root/.m2
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_REGION:
      AWS_SECRET_ACCESS_KEY:
      DEBUG:
      DOCKER_COMPOSE: 'true'
      FILTER_HOST:
      FILTER_PORT:
      PORT:
      STORAGE_HOST:
      STORAGE_PORT:
